# Generated by Django 3.2.5 on 2022-05-29 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='info',
            field=models.TextField(default=''),
        ),
    ]
